/**
 * DATABASE DELLE SCENE E LOCATION
 * Contiene gli scenari di improvvisazione divisi per tema.
 */

const LOCATIONS = {
  teatro: [
    "Un teatro dell'opera nel giorno della prima con il tenore che ha perso la voce",
    "Le quinte di un teatro di varietà durante l'emergenza del sipario bloccato",
    "Il palco di un grande circo svuotato con qualcuno che prova ancora da solo",
    "La platea di un cinema abbandonato con lo schermo che si illumina da solo",
    "Il camerino principale di un famoso teatro cinque minuti prima del sipario",
    "Un teatro di marionette dove le marionette si muovono senza fili",
    "Il backstage di un'enorme produzione di Broadway la sera della prima",
    "La cabina di regia di un teatro durante uno spettacolo che sta andando male",
    "I sotterranei di un teatro dell'opera con qualcosa che non torna",
    "La sartoria di un teatro durante la consegna dei costumi sbagliati",
    "Un teatro galleggiante sul Po che parte senza preavviso",
    "La fossa dell'orchestra durante la pausa del direttore",
    "Un teatro di varietà dove il presentatore ha perso la voce",
    "Il deposito attrezzi di un circo con animali di dubbia provenienza",
    "Il palco di uno stadio dopo che tutti se ne sono andati tranne uno",
    "Un teatro di strada in una piazza italiana durante il Ferragosto",
    "La cabina del suggeritore durante uno spettacolo shakespeariano caotico",
    "Un cinema drive-in disabitato con il film che parte da solo",
    "Il guardaroba di un teatro d'opera durante un cambio d'abito di emergenza",
    "Un teatro di burattini medievale dove i burattini parlano da soli",
    "Il palco di un teatrino scolastico dove gli adulti recitano come bambini",
    "Una sala prove dove qualcuno prova la stessa scena da quarant'anni",
    "Il foyer di un teatro durante l'intervallo con un segreto in ogni angolo",
    "Il palco di un teatro galleggiante durante una tempesta improvvisa",
    "Un anfiteatro romano dove si recita ancora come nel secondo secolo",
    "Il backstage di Sanremo dieci minuti prima dell'esibizione finale",
    "Una sala da concerto dove i sedili si spostano da soli durante le prove",
    "Il trucco di un teatro dove ogni specchio mostra qualcosa di diverso",
    "Un set televisivo di un talent show che nessuno ha vinto per vent'anni",
    "Il parcheggio di un cinema durante la prima di un film che scandalizzerà tutti"
  ],
  sacro: [
    "La navata di una cattedrale gotica durante una messa di mezzanotte non prevista",
    "Un convento di clausura dove qualcuno ha dimenticato la musica accesa tutta la notte",
    "La cripta di un monastero medievale con reliquie dal comportamento anomalo",
    "Il campanile di una chiesa diroccata che suona da solo ogni terzo giovedì",
    "Il coro di una basilica durante un esorcismo che va sorprendentemente bene",
    "Un confessionale con due persone con molto da raccontare e un solo prete",
    "La sacristia di una chiesa durante un matrimonio tra due persone completamente incompatibili",
    "Un tempio buddista dove la campana ha sviluppato un'opinione propria",
    "Il paradiso — sezione VIP — con lista d'attesa dall'inizio dei tempi",
    "Il purgatorio — zona d'attesa — con musica d'ambiente e riviste del 1987",
    "L'inferno — reparto burocratico — dove si compila il modulo per l'eternità",
    "Una chiesa di montagna durante una valanga che non arriva mai del tutto",
    "Il parlatorio di un monastero di clausura con una visita inaspettata",
    "Una cappella di campagna dove il parroco è più strano dei fedeli",
    "La cattedrale di Santiago durante il pellegrinaggio dell'anno più affollato",
    "Un tempio induista durante la festa dei colori con ospiti europei confusi",
    "Una sinagoga durante il bar mitzvah più complicato della storia",
    "Una moschea durante la preghiera del venerdì con il muezzin afono",
    "Un convento dove le suore gestiscono una startup di cucina fusion",
    "Un santuario sul mare dove le onde dicono cose ogni notte",
    "La biblioteca di un monastero medievale con un manoscritto che cambia testo",
    "Una cappella alpina frequentata da santi molto opinabili",
    "Il refettorio di un convento durante il digiuno collettivo rotto in anticipo",
    "Un eremo sul vulcano frequentato da un monaco di poche parole e molte idee",
    "Un tempio maya ricostruito che funziona ancora come non dovrebbe",
    "La sacrestia durante la preparazione di una messa di requiem non autorizzata",
    "Un pellegrinaggio a Lourdes con un miracolo che nessuno vuole ammettere",
    "Un convento tibetano durante la visita di un turista chiassoso e sincero",
    "Il campanile di una basilica rinascimentale con tre campane scordatissime",
    "Una chiesa rupestre siciliana dove vivono ancora qualcuno che non è un turista"
  ],
  magico: [
    "Una biblioteca magica dove i libri cambiano storia ogni volta che li apri",
    "Il laboratorio di un alchimista che ha perso il controllo dell'esperimento principale",
    "Un castello incantato dove le porte decidono da sole dove portare",
    "Una strega del bosco che gestisce uno sportello di assistenza al pubblico",
    "Un castello delle fate con problemi di umidità e fantasmi poco professionali",
    "Un limbo tutto bianco dove non si capisce mai che ore sono",
    "Il mercato delle fate dove si vende tutto tranne quello che cerchi",
    "Un labirinto magico che si rearrangia ogni volta che ti distragi",
    "La bottega di un mago in pensione che non riesce a smettere",
    "Un giardino incantato dove le piante hanno un'opinione su tutto",
    "Il fondo di un pozzo dei desideri che li prende troppo alla lettera",
    "Una torre di guardia dove la guardia non sa da che parte guardare",
    "Il bosco delle fate durante una lite secolare tra clan rivali",
    "Una grotta di draghi che hanno aperto un bed and breakfast",
    "Il castello di un re che dorme da cento anni con i cortigiani ancora svegli",
    "Un circo volante atterrato senza preavviso in un paesino",
    "La dimora di un fantasma incapace di spaventare chicchessia",
    "Un'isola che appare solo durante le eclissi di luna",
    "Il villaggio di streghe che hanno votato per smettere di fare del male",
    "Un'accademia di magia per adulti ritardatari",
    "Il deposito degli oggetti incantati dimenticati nei secoli",
    "Un albero che racconta storie diverse a chi ci passa sotto",
    "La dimora di un oracolo che non vuole rispondere",
    "Un portale tra mondi in un appartamento di Milano al terzo piano",
    "Una fontana che esaudisce i desideri sbagliati con grande precisione",
    "Il giardino di un castello dove le statue vivono solo di notte",
    "Un ponticello magico dove bisogna rispondere a tre indovinelli",
    "La casa di un genio della lampada in pensione anticipata",
    "Un bosco che ha le sue leggi e le fa rispettare",
    "Un'isola di sirene con una sindacalizzazione recente e molto agguerrita"
  ],
  locale: [
    "Una sala da ballo degli anni Quaranta dove tutti ballano ancora come se fosse ieri",
    "Il backstage di un talent show con una giuria che ha perso ogni speranza",
    "Un night club sottomarino frequentato da creature marine in smoking",
    "La mensa di una scuola per supereroi con poteri inutili e molto orgoglio",
    "Un ospedale dove i pazienti stanno meglio dei medici",
    "La sala operatoria di un chirurgo con la passione per il musical",
    "La reception di un hotel dove tutti i clienti sono chiaramente in fuga da qualcosa",
    "Il pronto soccorso di un ospedale psichiatrico dove il medico è il più strano di tutti",
    "Una casa di riposo dove gli anziani sanno cose che nessuno vuole sapere",
    "Il reparto pediatria di un ospedale durante una visita di un clown non autorizzato",
    "Una palestra di pugilato dove tutti si allenano a qualcosa di non fisico",
    "Il bar di un piccolo aeroporto durante il ritardo più lungo della storia",
    "Una banca durante una rapina gestita da ladri molto cortesi",
    "Un ristorante stellato con un cuoco che ha perso l'ispirazione oggi",
    "Una scuola guida dove l'istruttore non ha mai guidato in città",
    "Il parcheggio di un supermercato la sera della vigilia di Natale",
    "Un condominio durante la riunione di condominio più epica della storia",
    "La sala d'aspetto di un ufficio postale dove tutti conoscono qualcuno",
    "Un ufficio open space durante l'ultimo venerdì prima delle ferie",
    "La sala comune di un ostello low-cost con ospiti di dodici nazioni",
    "Un club di lettura dove nessuno ha letto il libro",
    "La cucina di una trattoria napoletana durante il pranzo della domenica",
    "Un mercato rionale durante uno sciopero dei venditori",
    "Una biblioteca comunale dove qualcuno non restituisce un libro da quarant'anni",
    "Il reparto di chirurgia estetica dove tutti si travestono da qualcun altro",
    "Una palestra di yoga dove il maestro ha perso la voce",
    "Un laundromat di quartiere alle tre di mattina con clienti insoliti",
    "La sala fumare di un ospedale dove i malati consolano i medici",
    "Un ristorante cinese durante il capodanno lunare con un ospite fantasma",
    "Il bagno di un night club con una coda di due ore e molti segreti",
    "Un call center durante la campagna di sondaggi più strana dell'anno",
    "La sala di un notaio durante una lettura di testamento inaspettata",
    "Un taxi durante un viaggio di tre ore con il tassista che sa tutto"
  ],
  storico: [
    "Le trincee della Prima Guerra Mondiale durante una tregua di Natale improvvisata",
    "La corte di un re medievale durante un processo per stregoneria un po' ambiguo",
    "Un manicomio vittoriano dove il personale è più matto dei pazienti",
    "La prigione di una fortezza rinascimentale con un'evasione in corso molto disorganizzata",
    "Un orfanotrofio dickensiano con una donazione inaspettata e molto sospetta",
    "La sala del trono di un impero sul viale del tramonto con la corte ancora lì",
    "Un monastero medievale durante l'invasione di un esercito che non sa cosa fare dopo",
    "Il palazzo reale durante un colpo di stato molto educato e formale",
    "La piazza di un paese medievale durante la lettura di un editto incomprensibile",
    "Un castello assediato dove i difensori hanno finito le idee ma non il coraggio",
    "La stiva di una nave negriera americana con una rivolta in corso",
    "Un campo di concentramento durante il giorno della liberazione inaspettata",
    "La corte di Cleopatra durante la visita di un ambasciatore romano perso",
    "Un banchetto rinascimentale dove qualcuno ha avvelenato il vino sbagliato",
    "La sala del senato di Roma durante la congiura delle congiure",
    "Un porto di pirati nel Seicento durante la divisione del bottino sbagliata",
    "Una carovana della Via della Seta durante la carestia più creativa della storia",
    "Il parlamento inglese durante la rivoluzione più educata che ci sia mai stata",
    "Una taverna medievale dove si trama qualcosa di grosso e molto rumoroso",
    "Le catacombe romane durante un rituale che non si dovrebbe fare",
    "Il mercato degli schiavi di Atene dove qualcuno si rifiuta di essere venduto",
    "Una corte del Rinascimento dove Machiavelli dà consigli non richiesti",
    "Il castello di Chambord durante la sua costruzione con architetti che litigano",
    "La cucina di un palazzo borbonico durante la preparazione del banchetto finale",
    "Una caserma napoleonica la mattina di Waterloo con qualcuno che non ci crede",
    "Il salone di una villa fascista durante una riunione clandestina",
    "Un trenino del Far West durante la corsa all'oro con passeggeri improbabili",
    "La Bastiglia la sera prima della rivoluzione con le guardie che giocano a carte",
    "Il porto di Genova durante la partenza dell'ultima galea",
    "Una bottega di Pompei il mattino del 24 agosto del 79 d.C.",
    "Il Campo de' Fiori la notte prima dell'esecuzione di Giordano Bruno",
    "La stazione di Leipzig il giorno della partenza degli ultimi ebrei"
  ],
  esotico: [
    "Il mercato delle spezie di una medina nord-africana alle tre di notte",
    "Una favela brasiliana durante i preparativi per il Carnevale più caotico di sempre",
    "Una capanna sugli alberi nell'Amazzonia durante un incontro diplomatico segreto",
    "Il deserto del Gobi in mezzo a una tempesta di sabbia con una carovana perduta",
    "Una stazione balneare fuori stagione con un solo hotel aperto e un solo cliente",
    "Il porto di pescatori di un'isola greca in una disputa con i gabbiani locali",
    "Un villaggio fantasma nel Far West con un solo abitante che gestisce tutto",
    "Un bazar turco dove tutto è in saldo ma niente è quello che sembra",
    "Un ryokan giapponese dove le regole non sono scritte ma tutti le conoscono tranne te",
    "Un souk di Marrakech dove un venditore conosce il tuo nome senza che tu glielo abbia detto",
    "Una riserva indiana in Nevada dove si punta su qualcosa che non è il blackjack",
    "Il porto di pesca di un'isola delle Azzorre durante la migrazione delle balene",
    "Un risciò ad Hong Kong con un autista che conosce tutte le strade e qualcosa di più",
    "Un mercato notturno di Bangkok con cibo impossibile e clienti improbabili",
    "La piazza principale di un pueblo messicano durante il Día de Muertos",
    "Un train gare di Calcutta alle 5 di mattina con destinazione incerta",
    "Una capanna inuit durante la notte polare più lunga dell'anno",
    "Un hammam turco dove il massaggiatore racconta storie incredibili",
    "Il porto di Zanzibar durante un tramonto che dura tre ore inspiegabili",
    "Una steppe mongola durante la migrazione annuale con un ospite italiano perso",
    "Un tempio di Angkor Wat durante la stagione delle piogge e delle visioni",
    "Il bazàr di Samarcanda durante la carovana che non dovrebbe essere lì",
    "Una casa galleggiante sul Mekong con più ospiti di quanti possano starci",
    "Un mercato dei fiori a Kolkata all'alba con venditori che litigano in cinque lingue",
    "Il souk dei profumi di Dubai con un venditore che sa cosa vuoi prima che tu parli",
    "Un villaggio berbero sull'Atlante durante la festa di capodanno berbero",
    "La laguna di Venezia durante l'acqua alta con i turisti che non capiscono",
    "Un porto di pesca siciliano alle 4 di mattina con il pescato dell'anno",
    "Una stazione sciistica spagnola fuori stagione con un solo impianto aperto",
    "Il porto di Rio de Janeiro durante il montaggio del palco del Carnevale",
    "Un hacienda peruviana durante la raccolta della coca legale e molto discussa",
    "Un'isola delle Maldive dove il personale sa tutto degli ospiti ma non dice niente"
  ],
  fantascientifico: [
    "Una stazione spaziale in orbita decadente con il wi-fi che non va mai",
    "Un laboratorio segreto dove l'esperimento principale ha preso l'iniziativa da solo",
    "Una colonia su Marte nel giorno dell'inaugurazione del primo ristorante",
    "Il ponte di comando di una nave stellare con equipaggio in ammutinamento creativo",
    "Un bunker nucleare degli anni '60 dove i superstiti non sanno ancora che è finita",
    "Un robot che ha appena scoperto le emozioni e non sa assolutamente cosa farsene",
    "Una macchina del tempo con il navigatore rotto e nessuna garanzia di ritorno",
    "Una città sotto una cupola di vetro dove piove solo il martedì, per regolamento",
    "Un pianeta di soli robot che hanno appena scoperto il libero arbitrio",
    "Una sala di controllo di un'intelligenza artificiale che ha smesso di obbedire",
    "Il corridoio di un ospedale spaziale dove i chirurghi sono tutti ologrammi",
    "Un asteroide minerario con i lavoratori in sciopero per motivi cosmici",
    "Il mercato nero di una colonia lunare dove si vende aria",
    "Un'astronave di rifugiati interstellari in cerca di pianeta",
    "Una base antartica del 2150 dove il ghiaccio è tornato",
    "Il parlamento di una federazione galattica durante il voto più controverso della storia",
    "Un pianeta dove gli umani sono in gabbia e gli alieni vengono a vederli",
    "La sala server di un'IA che ha deciso di scrivere poesia invece di lavorare",
    "Un treno su rotaia magnetica che attraversa cinque stati in quindici minuti",
    "Un ufficio del futuro dove tutti lavorano dal metaverso tranne uno",
    "Il cantiere di una megastruttura orbitale con i sindacati del futuro",
    "Una scuola per bambini nati nello spazio che non hanno mai visto la Terra",
    "Una cupola agricola su Venere con un problema di temperatura molto gestibile",
    "La sala macchine di un sommergibile del 2200 con qualcosa di vivo nel motore",
    "Una città fluttuante nell'atmosfera di Giove con problemi di affitto",
    "Il centro di smistamento di una posta interstellare con un pacco impossibile",
    "Una clinica di modificazioni genetiche dove il medico si è modificato troppe volte",
    "Il porto spaziale di Titan con dogana e lunghe code",
    "Una base lunare in stile anni '70 dove si è rimasti fermi a quella tecnologia",
    "Un pianeta dove la musica è moneta corrente"
  ]
};

const ALL_LOC = Object.values(LOCATIONS).flat();
